export const STAGES = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    color: 'bg-gray-500',
    activeColor: 'bg-gray-700',
    hoverColor: 'hover:bg-gray-600',
    table: null,
    nextStage: null,
    promoteLabel: null,
  },
  {
    key: 'orders',
    label: 'Orders',
    color: 'bg-blue-500',
    activeColor: 'bg-blue-700',
    hoverColor: 'hover:bg-blue-600',
    table: 'orders',
    nextStage: 'received',
    promoteLabel: 'Mark Received',
    promoteCondition: () => true,
  },
  {
    key: 'received',
    label: 'Received',
    color: 'bg-green-500',
    activeColor: 'bg-green-700',
    hoverColor: 'hover:bg-green-600',
    table: 'received',
    nextStage: 'testing',
    promoteLabel: 'Send to Testing',
    promoteCondition: () => true,
  },
  {
    key: 'testing',
    label: 'Testing',
    color: 'bg-orange-500',
    activeColor: 'bg-orange-700',
    hoverColor: 'hover:bg-orange-600',
    table: 'testing',
    nextStage: 'approved',
    promoteLabel: 'Approve',
    promoteCondition: (row) => row.pass_fail === 'pass',
  },
  {
    key: 'approved',
    label: 'Approved',
    color: 'bg-cyan-500',
    activeColor: 'bg-cyan-700',
    hoverColor: 'hover:bg-cyan-600',
    table: 'approved',
    nextStage: 'on_website',
    promoteLabel: 'List on Website',
    promoteCondition: () => true,
  },
  {
    key: 'on_website',
    label: 'On Website',
    color: 'bg-lime-500',
    activeColor: 'bg-lime-700',
    hoverColor: 'hover:bg-lime-600',
    table: 'on_website',
    nextStage: null,
    promoteLabel: null,
  },
  {
    key: 'audit_log',
    label: 'Audit Log',
    color: 'bg-red-500',
    activeColor: 'bg-red-700',
    hoverColor: 'hover:bg-red-600',
    table: 'audit_log',
    nextStage: null,
    promoteLabel: null,
  },
]

export const USERS = ['Camila', 'Aiden', 'Peyton', 'Admin']

export const STATUS_LABELS = {
  ordered: 'Ordered',
  received: 'Received',
  in_testing: 'In Testing',
  approved: 'Approved',
  live: 'On Website',
  failed: 'Failed',
}
